server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/streamapi
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

files:
  video: "videos/"

file:
  video:
    hsl: "videos_hsl/"
